name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      env:
        SUPER_LOGIN: ${{ secrets.BASIC_AUTH_USERNAME }}
        SUPER_SECRET: ${{ secrets.BASIC_AUTH_PASSWORD }}
      run: |
        npm i
        npm run build
        script=`cat build/EventHelperV2.user.js`
        curl -X POST https://${SUPER_LOGIN}:${SUPER_SECRET}@hwm.events/updateScript -d $script
